services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - monitoring_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
    volumes:
      - grafana_data:/var/lib/grafana

  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    tty: true
    networks:
      - monitoring_net
    volumes:
      - net_admin:/app

networks:
  monitoring_net:
    driver: bridge

volumes:
  net_admin:
  grafana_data:

